version: "3.9"

services:

  blog:
    build:
      context: .
      dockerfile: ./docker-build/blog/Dockerfile
    ports:
      - "8000:80"
    command: "gunicorn app:app --bind=0.0.0.0:80"
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    user: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
